import React, { useState } from 'react';
import {
  BusFront, CalendarClock, Check, CircleAlert, KeyRound, LogOut, MapPinned,
  Pencil, Plus, Route, ShieldCheck, Trash2, UsersRound, X,
} from 'lucide-react';
import { DatscoLogo } from '../../assets/svg/DatscoLogo';
import { RouteMapPicker } from './RouteMapPicker';
import { TerminalLocationPicker } from './TerminalLocationPicker';
import { RouteWaypoint, Terminal, TransitRoute, useTransit } from '../../contexts/TransitContext';

type Section = 'overview' | 'routes' | 'schedules' | 'terminals' | 'drivers' | 'security';
type Notice = { error?: boolean; text: string } | null;
type RouteDraft = Omit<TransitRoute, 'id' | 'coordinates'>;

const inputClass = 'mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-blue-500 focus:bg-white focus:ring-2 focus:ring-blue-100';
const labelClass = 'block text-xs font-bold text-slate-600';
const blankRoute: RouteDraft = { title: '', origin: '', destination: '', originTerminalId: '', destinationTerminalId: '', type: 'bus', fare: 0, discountedFare: null, eta: '', duration: '', available: true };
const asDraft = (route: TransitRoute): RouteDraft => ({ title: route.title, origin: route.origin, destination: route.destination, originTerminalId: route.originTerminalId, destinationTerminalId: route.destinationTerminalId, type: route.type, fare: route.fare, discountedFare: route.discountedFare, eta: route.eta, duration: route.duration, available: route.available });

function RouteManager({ onNotice }: { onNotice: (message: string, error?: boolean) => void }) {
  const { routes, terminals, addRoute, updateRoute } = useTransit();
  const [draft, setDraft] = useState<RouteDraft>(blankRoute);
  const [waypoints, setWaypoints] = useState<RouteWaypoint[]>([]);
  const [editingId, setEditingId] = useState<string | null>(null);
  const origin = terminals.find((terminal) => terminal.id === draft.originTerminalId);
  const destination = terminals.find((terminal) => terminal.id === draft.destinationTerminalId);
  const reset = () => { setDraft(blankRoute); setWaypoints([]); setEditingId(null); };
  const edit = (route: TransitRoute) => { setDraft(asDraft(route)); setWaypoints(route.waypoints ?? route.coordinates.slice(1, -1).map(([latitude, longitude], index) => ({ id: `legacy-${route.id}-${index}`, latitude, longitude, label: `Passing point ${index + 1}` }))); setEditingId(route.id); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const selectOrigin = (terminal: Terminal) => setDraft((current) => ({ ...current, origin: terminal.name, originTerminalId: terminal.id }));
  const selectDestination = (terminal: Terminal) => setDraft((current) => ({ ...current, destination: terminal.name, destinationTerminalId: terminal.id }));
  const save = (event: React.FormEvent) => {
    event.preventDefault();
    if (!draft.title.trim() || !origin || !destination || !draft.eta.trim() || !draft.duration.trim() || draft.fare < 0) return onNotice('Add a route name, select both terminals on the map, and complete the route details.', true);
    if (draft.discountedFare !== null && (draft.discountedFare < 0 || draft.discountedFare > draft.fare)) return onNotice('The discounted fare must be between ₱0 and the regular fare.', true);
    const payload = { ...draft, title: draft.title.trim(), waypoints, coordinates: [[origin.latitude, origin.longitude] as [number, number], ...waypoints.map((point) => [point.latitude, point.longitude] as [number, number]), [destination.latitude, destination.longitude] as [number, number]] };
    if (editingId) { updateRoute(editingId, payload); onNotice('Route changes saved.'); } else { addRoute(payload); onNotice('New route created and saved.'); }
    reset();
  };
  return <div className="space-y-6">
    <form onSubmit={save} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
      <div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-black">{editingId ? 'Edit route' : 'Add a new route'}</h2><p className="mt-1 text-xs leading-5 text-slate-500">Choose the terminals, trace the route road-by-road on the Siargao map, name the passing points, then save the passenger-visible path.</p></div>{editingId && <button type="button" onClick={reset} className="rounded-xl p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700" aria-label="Cancel route edit"><X size={18} /></button>}</div>
      <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label className={labelClass}>Route name<input required value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="Dapa → General Luna" className={inputClass} /></label><label className={labelClass}>Service type<select value={draft.type} onChange={(event) => setDraft({ ...draft, type: event.target.value as 'bus' | 'ferry' })} className={inputClass}><option value="bus">Bus</option><option value="ferry">Ferry</option></select></label><label className={labelClass}>Regular fare (₱)<input required type="number" min="0" value={draft.fare} onChange={(event) => setDraft({ ...draft, fare: Number(event.target.value) || 0 })} className={inputClass} /></label><label className={labelClass}>Discounted fare (₱)<input type="number" min="0" max={draft.fare} value={draft.discountedFare ?? ''} onChange={(event) => setDraft({ ...draft, discountedFare: event.target.value === '' ? null : Number(event.target.value) })} placeholder="Optional" className={inputClass} /></label><label className={labelClass}>Estimated time<input required value={draft.eta} onChange={(event) => setDraft({ ...draft, eta: event.target.value })} placeholder="30 mins" className={inputClass} /></label><label className={labelClass}>Duration badge<input required value={draft.duration} onChange={(event) => setDraft({ ...draft, duration: event.target.value })} placeholder="30 min" className={inputClass} /></label><label className="mt-5 flex items-center gap-2 text-sm font-bold text-slate-700"><input type="checkbox" checked={draft.available} onChange={(event) => setDraft({ ...draft, available: event.target.checked })} className="h-4 w-4 rounded border-slate-300 text-blue-600" />Route available</label><div className="md:col-span-2 xl:col-span-2 rounded-xl border border-slate-100 bg-slate-50 px-3 py-2 text-xs text-slate-600"><b>Origin:</b> {draft.origin || 'Select terminal A on the map'}<br /><b>Destination:</b> {draft.destination || 'Select terminal B on the map'}</div></div>
      <RouteMapPicker terminals={terminals} originTerminalId={draft.originTerminalId} destinationTerminalId={draft.destinationTerminalId} points={waypoints} onOriginChange={selectOrigin} onDestinationChange={selectDestination} onPointsChange={setWaypoints} />
      {waypoints.length > 0 && <section className="mt-4 rounded-2xl border border-blue-100 bg-blue-50/50 p-4"><div><p className="text-sm font-black text-slate-800">Passing points</p><p className="mt-1 text-xs text-slate-500">Name the landmarks, barangays, or junctions passengers should recognize. Use the arrows to set the travel order.</p></div><div className="mt-3 space-y-2">{waypoints.map((waypoint, index) => <div key={waypoint.id} className="flex flex-wrap items-center gap-2 rounded-xl bg-white p-2.5 ring-1 ring-slate-100"><span className="h-3 w-3 rounded-full bg-slate-700" aria-hidden="true" /><input value={waypoint.label} onChange={(event) => setWaypoints((current) => current.map((point, pointIndex) => pointIndex === index ? { ...point, label: event.target.value } : point))} placeholder="Passing point (e.g. Libertad junction)" className="min-w-48 flex-1 rounded-lg border border-slate-200 px-3 py-1.5 text-xs text-slate-800 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /><span className="text-[10px] text-slate-400">{waypoint.latitude.toFixed(5)}, {waypoint.longitude.toFixed(5)}</span><button type="button" disabled={index === 0} onClick={() => setWaypoints((current) => { const next = [...current]; [next[index - 1], next[index]] = [next[index], next[index - 1]]; return next; })} className="rounded-lg px-2 py-1 text-xs font-bold text-slate-500 hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-30">↑</button><button type="button" disabled={index === waypoints.length - 1} onClick={() => setWaypoints((current) => { const next = [...current]; [next[index], next[index + 1]] = [next[index + 1], next[index]]; return next; })} className="rounded-lg px-2 py-1 text-xs font-bold text-slate-500 hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-30">↓</button><button type="button" onClick={() => setWaypoints((current) => current.filter((_, pointIndex) => pointIndex !== index))} className="rounded-lg px-2 py-1 text-xs font-bold text-red-600 hover:bg-red-50">Remove</button></div>)}</div></section>}
      <button className="mt-5 flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white transition hover:bg-blue-700 active:scale-[.98]"><Plus size={17} />{editingId ? 'Save route changes' : 'Create and save route'}</button>
    </form>
    <div className="grid gap-4 xl:grid-cols-2">{routes.map((route) => <article key={route.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-black">{route.title}</p><p className="mt-1 text-xs text-slate-500">{route.origin} to {route.destination} · Regular ₱{route.fare}{route.discountedFare !== null && ` · Discounted ₱${route.discountedFare}`} · {route.eta}</p><p className="mt-2 text-xs font-semibold text-blue-700">{route.waypoints?.length ?? Math.max(0, route.coordinates.length - 2)} mapped passing point{(route.waypoints?.length ?? Math.max(0, route.coordinates.length - 2)) === 1 ? '' : 's'}</p></div><div className="flex items-center gap-2"><button type="button" onClick={() => updateRoute(route.id, { available: !route.available })} className={`rounded-full px-3 py-1.5 text-xs font-bold ${route.available ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{route.available ? 'Available' : 'Unavailable'}</button><button type="button" onClick={() => edit(route)} className="rounded-xl border border-blue-200 p-2 text-blue-600 hover:bg-blue-50" aria-label={`Edit ${route.title}`}><Pencil size={17} /></button></div></div></article>)}</div>
  </div>;
}

function TerminalManager({ onNotice }: { onNotice: (message: string, error?: boolean) => void }) {
  const { terminals, routes, addTerminal, updateTerminal, deleteTerminal } = useTransit();
  const [draft, setDraft] = useState({ name: '', details: '', point: null as { latitude: number; longitude: number } | null });
  const [editingId, setEditingId] = useState<string | null>(null);
  const reset = () => { setDraft({ name: '', details: '', point: null }); setEditingId(null); };
  const edit = (terminal: Terminal) => { setEditingId(terminal.id); setDraft({ name: terminal.name, details: terminal.details, point: { latitude: terminal.latitude, longitude: terminal.longitude } }); };
  const save = (event: React.FormEvent) => { event.preventDefault(); if (!draft.name.trim() || !draft.point) return onNotice('Enter a terminal name, then click the Siargao map to select its location.', true); const payload = { name: draft.name.trim(), details: draft.details.trim() || 'Operating details not provided', ...draft.point }; if (editingId) { updateTerminal(editingId, payload); onNotice('Terminal changes saved.'); } else { addTerminal(payload); onNotice('Terminal added to the passenger map.'); } reset(); };
  const remove = (terminal: Terminal) => {
    const affectedRoutes = routes.filter((route) => route.originTerminalId === terminal.id || route.destinationTerminalId === terminal.id).map((route) => route.title);
    if (affectedRoutes.length > 0) {
      onNotice(`This terminal cannot be deleted. It is used by: ${affectedRoutes.join(', ')}. Edit or remove those routes first.`, true);
      return;
    }
    if (!window.confirm(`Delete ${terminal.name} from the passenger map? This cannot be undone.`)) return;
    const result = deleteTerminal(terminal.id);
    if (!result.ok) return onNotice('This terminal can no longer be deleted because a route now uses it.', true);
    if (editingId === terminal.id) reset();
    onNotice('Terminal deleted from map data.');
  };
  return <div className="grid gap-6 xl:grid-cols-[1fr_.9fr]"><form onSubmit={save} className="h-fit rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="font-black">{editingId ? 'Edit terminal' : 'Add terminal'}</h2><p className="mt-1 text-xs text-slate-500">Click the map, review the pin coordinates, then confirm to save.</p></div>{editingId && <button type="button" onClick={reset} className="rounded-xl p-2 text-slate-400 hover:bg-slate-100"><X size={18} /></button>}</div><div className="mt-4 space-y-3"><input required value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} placeholder="Terminal name" className={inputClass} /><input value={draft.details} onChange={(event) => setDraft({ ...draft, details: event.target.value })} placeholder="Operating details" className={inputClass} /><TerminalLocationPicker value={draft.point} onChange={(point) => setDraft({ ...draft, point })} /><button className="flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 py-3 text-sm font-bold text-white hover:bg-blue-700"><MapPinned size={17} />{editingId ? 'Confirm location update' : 'Confirm and add terminal'}</button></div></form><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black">Passenger map terminals</h2><div className="mt-4 space-y-3">{terminals.map((terminal) => <article key={terminal.id} className="flex items-center justify-between gap-3 rounded-2xl border border-slate-200 p-4"><div><p className="font-black">{terminal.name}</p><p className="mt-1 text-xs text-slate-500">{terminal.latitude.toFixed(5)}, {terminal.longitude.toFixed(5)}</p><p className="mt-1 text-xs text-slate-500">{terminal.details}</p></div><div className="flex gap-2"><button type="button" onClick={() => edit(terminal)} className="rounded-xl border border-blue-200 p-2 text-blue-600 hover:bg-blue-50" aria-label={`Edit ${terminal.name} location`}><Pencil size={17} /></button><button type="button" onClick={() => remove(terminal)} className="rounded-xl border border-red-200 p-2 text-red-600 hover:bg-red-50" aria-label={`Delete ${terminal.name}`}><Trash2 size={17} /></button></div></article>)}</div></section></div>;
}

export const AdminDashboard: React.FC<{ onLogout: () => void }> = ({ onLogout }) => {
  const { currentUser, accounts, routes, schedules, terminals, activeTrips, contact, createDriver, deleteDriver, setAdminPassword, addSchedule, deleteSchedule, updateContact } = useTransit();
  const [section, setSection] = useState<Section>('overview');
  const [notice, setNotice] = useState<Notice>(null);
  const [driver, setDriver] = useState({ displayName: '', username: '', password: '' });
  const [schedule, setSchedule] = useState({ routeId: routes[0]?.id ?? '', time: '', period: 'Morning' as 'Morning' | 'Afternoon', days: 'Monday – Saturday' });
  const [password, setPassword] = useState({ current: '', next: '' });
  const drivers = accounts.filter((account) => account.role === 'driver');
  const liveTripCount = activeTrips.filter((trip) => trip.status === 'departed').length;
  const arrivedTripCount = activeTrips.filter((trip) => trip.status === 'arrived').length;
  const inform = (text: string, error = false) => { setNotice({ text, error }); window.setTimeout(() => setNotice(null), 3500); };
  const nav: Array<[Section, string, typeof Route]> = [['overview', 'Overview', ShieldCheck], ['routes', 'Routes & fares', Route], ['schedules', 'Schedules', CalendarClock], ['terminals', 'Terminals', MapPinned], ['drivers', 'Drivers', UsersRound], ['security', 'Security', KeyRound]];
  const routeLabel = (routeId: string) => routes.find((route) => route.id === routeId)?.title ?? 'Unknown route';
  const createNewDriver = async (event: React.FormEvent) => { event.preventDefault(); const result = await createDriver(driver); if (!result.ok) return inform(result.error ?? 'Unable to register driver.', true); setDriver({ displayName: '', username: '', password: '' }); inform('Driver account registered.'); };
  const createSchedule = (event: React.FormEvent) => { event.preventDefault(); if (!schedule.routeId || !schedule.time.trim()) return inform('Select a route and enter a time slot.', true); addSchedule({ ...schedule, time: schedule.time.trim() }); setSchedule((current) => ({ ...current, time: '' })); inform('Schedule added.'); };
  const changePassword = async (event: React.FormEvent) => { event.preventDefault(); const result = await setAdminPassword(password.current, password.next); if (!result.ok) return inform(result.error ?? 'Unable to update password.', true); setPassword({ current: '', next: '' }); inform('Administrator password updated.'); };
  if (currentUser?.role !== 'admin') return <main className="grid min-h-screen place-items-center bg-slate-50 p-6"><section className="max-w-sm rounded-3xl bg-white p-6 text-center shadow-xl"><ShieldCheck className="mx-auto text-blue-600" size={34} /><h1 className="mt-3 text-xl font-black">Administrator access required</h1><button onClick={onLogout} className="mt-5 rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">Return to DatscoGo</button></section></main>;
  return <main className="min-h-[100dvh] bg-slate-100 text-slate-900 lg:flex"><aside className="flex shrink-0 flex-col bg-[#102a56] p-4 text-white lg:w-72 lg:p-5"><div className="flex items-center gap-3 px-2 py-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-500"><DatscoLogo size={25} color="#fff" /></span><div><p className="text-lg font-black">Datsco<span className="text-blue-300">Go</span></p><p className="text-[10px] font-bold uppercase tracking-[.15em] text-slate-400">Admin workspace</p></div></div><nav className="mt-5 flex gap-2 overflow-x-auto pb-1 lg:flex-col">{nav.map(([id, label, Icon]) => <button key={id} onClick={() => setSection(id)} className={`flex shrink-0 items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-bold transition active:scale-[.98] ${section === id ? 'bg-blue-600 shadow-lg shadow-blue-950/30' : 'text-slate-300 hover:bg-white/10 hover:text-white'}`}><Icon size={18} />{label}</button>)}</nav><div className="mt-auto hidden border-t border-white/10 pt-4 lg:block"><p className="px-3 text-xs font-bold">{currentUser.displayName}</p><button onClick={onLogout} className="mt-3 flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-sm font-bold text-slate-300 hover:bg-white/10 hover:text-white"><LogOut size={17} />Logout</button></div></aside><section className="min-w-0 flex-1 p-4 sm:p-6 lg:p-8"><header className="mb-6 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-blue-600">DatscoGo management</p><h1 className="mt-1 text-2xl font-black tracking-tight sm:text-3xl">{nav.find(([id]) => id === section)?.[1]}</h1></div><button onClick={onLogout} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-600 lg:hidden"><LogOut className="mr-1 inline" size={15} />Logout</button></header>{notice && <div role="status" className={`mb-5 flex items-center gap-2 rounded-2xl border px-4 py-3 text-sm font-bold ${notice.error ? 'border-red-200 bg-red-50 text-red-800' : 'border-emerald-200 bg-emerald-50 text-emerald-800'}`}>{notice.error ? <CircleAlert size={17} /> : <Check size={17} />}{notice.text}</div>}
    {section === 'overview' && <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[Route, 'Available routes', `${routes.filter((item) => item.available).length} / ${routes.length}`], [CalendarClock, 'Schedule entries', schedules.length], [MapPinned, 'Map terminals', terminals.length], [UsersRound, 'Driver accounts', drivers.length]].map(([Icon, label, value]) => { const MetricIcon = Icon as typeof Route; return <article key={label as string} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><span className="inline-flex rounded-xl bg-blue-50 p-2.5 text-blue-600"><MetricIcon size={20} /></span><p className="mt-4 text-2xl font-black">{value as string | number}</p><p className="mt-1 text-xs font-bold uppercase tracking-[.1em] text-slate-500">{label as string}</p></article>; })}</div><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-base font-black">Vehicle trips</h2><p className="mt-2 text-sm text-slate-600">{activeTrips.length ? `${liveTripCount} live vehicle${liveTripCount === 1 ? '' : 's'} and ${arrivedTripCount} vehicle${arrivedTripCount === 1 ? '' : 's'} at destination.` : 'No driver is currently reporting an active trip.'}</p></article><article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-base font-black">Public contact details</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><input value={contact.facebook} onChange={(event) => updateContact({ ...contact, facebook: event.target.value })} placeholder="Facebook page" className={inputClass} /><input value={contact.phone} onChange={(event) => updateContact({ ...contact, phone: event.target.value })} placeholder="Contact number" className={inputClass} /><input type="email" value={contact.email} onChange={(event) => updateContact({ ...contact, email: event.target.value })} placeholder="Email address" className={inputClass} /></div></article></div>}
    {section === 'routes' && <RouteManager onNotice={inform} />}
    {section === 'terminals' && <TerminalManager onNotice={inform} />}
    {section === 'schedules' && <div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><form onSubmit={createSchedule} className="h-fit rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black">Add schedule entry</h2><div className="mt-4 space-y-3"><select value={schedule.routeId} onChange={(event) => setSchedule({ ...schedule, routeId: event.target.value })} className={inputClass}>{routes.map((route) => <option key={route.id} value={route.id}>{route.title}</option>)}</select><input required value={schedule.time} onChange={(event) => setSchedule({ ...schedule, time: event.target.value })} placeholder="6:30 – 7:00am" className={inputClass} /><select value={schedule.period} onChange={(event) => setSchedule({ ...schedule, period: event.target.value as 'Morning' | 'Afternoon' })} className={inputClass}><option>Morning</option><option>Afternoon</option></select><button className="flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 py-3 text-sm font-bold text-white hover:bg-blue-700"><Plus size={17} />Add schedule</button></div></form><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black">Current schedule entries</h2><div className="mt-4 divide-y divide-slate-100">{schedules.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-bold">{routeLabel(item.routeId)}</p><p className="text-xs text-slate-500">{item.period} · {item.time} · {item.days}</p></div><button type="button" onClick={() => deleteSchedule(item.id)} className="rounded-xl p-2 text-slate-400 hover:bg-red-50 hover:text-red-600" aria-label="Delete schedule"><Trash2 size={17} /></button></div>)}</div></section></div>}
    {section === 'drivers' && <div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><form onSubmit={createNewDriver} className="h-fit rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black">Register driver</h2><div className="mt-4 space-y-3"><input required value={driver.displayName} onChange={(event) => setDriver({ ...driver, displayName: event.target.value })} placeholder="Driver name" className={inputClass} /><input required value={driver.username} onChange={(event) => setDriver({ ...driver, username: event.target.value })} placeholder="Username" className={inputClass} /><input required type="password" value={driver.password} onChange={(event) => setDriver({ ...driver, password: event.target.value })} placeholder="Temporary password (8+ characters)" className={inputClass} /><button className="flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 py-3 text-sm font-bold text-white hover:bg-blue-700"><Plus size={17} />Create driver account</button></div></form><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black">Registered drivers</h2><div className="mt-4 divide-y divide-slate-100">{drivers.map((driverItem) => <div key={driverItem.id} className="flex items-center justify-between gap-3 py-3"><div className="flex items-center gap-3"><span className="rounded-xl bg-blue-50 p-2.5 text-blue-600"><BusFront size={18} /></span><div><p className="text-sm font-bold">{driverItem.displayName}</p><p className="text-xs text-slate-500">@{driverItem.username}</p></div></div><button type="button" onClick={() => { if (window.confirm(`Delete ${driverItem.displayName}'s driver account? This cannot be undone.`)) { deleteDriver(driverItem.id); inform('Driver account deleted.'); } }} className="rounded-xl border border-red-200 p-2 text-red-600 transition hover:bg-red-50" aria-label={`Delete ${driverItem.displayName}`}><Trash2 size={17} /></button></div>)}</div></section></div>}
    {section === 'security' && <form onSubmit={changePassword} className="max-w-xl rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="flex items-center gap-2 text-sm font-black text-amber-900"><KeyRound size={17} />Replace starter credential</p><p className="mt-1 text-xs leading-5 text-amber-800">Change the simple setup password before using the app beyond demonstration.</p></div><div className="mt-5 space-y-3"><input required type="password" value={password.current} onChange={(event) => setPassword({ ...password, current: event.target.value })} placeholder="Current password" className={inputClass} /><input required type="password" minLength={10} value={password.next} onChange={(event) => setPassword({ ...password, next: event.target.value })} placeholder="New password (10+ characters)" className={inputClass} /><button className="flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 py-3 text-sm font-bold text-white hover:bg-blue-700"><KeyRound size={17} />Update administrator password</button></div></form>}
    </section></main>;
};
